#ifndef _SEALCONFIG_H
#define _SEALCONFIG_H

#define SEALINFO 1

#define SEAL_CORE_MAXSTRLEN (256)
#define SEAL_IO_MAXPATHLEN (64)
#define SEAL_INFO_MAXLEN (1024)

#define SEAL_SYM_EVENT_STRING_DELIMITER (":")

#define SEAL_SCRIPT_LINE_MARK_STYLE ("<%s>")
#define SEAL_SCRIPT_BLOCK_MARK_STYLE ("<%s>")
#define SEAL_SCRIPT_EOL ('\n')
#define SEAL_SCRIPT_EOB ("\0")
#define SEAL_SCRIPT_MARK_LEN (255)
#define SEAL_SCRIPT_MAX_LINE_LEN (1024)

#endif
